// Generated by CoffeeScript 1.6.3
var sync_object;

sync_object = {
  "GDrive": {
    "app_id": "64840406425",
    "key": "64840406425-l292ah0o3tt1idacjdru6lrib3ljdkl7.apps.googleusercontent.com",
    "scope": "https://www.googleapis.com/auth/drive",
    "app_name": "jellyreader"
  },
  "Dropbox": {
    "key": "q5yx30gr8mcvq4f",
    "secret": "qy64qphr70lwui5",
    "app_name": "jellyreader"
  }
};

Nimbus.Auth.setup(sync_object);
